[template]
src = "env.tmpl"
dest = "/usr/src/app/config/env"
keys = [
  "/resin/api/host",
  "/resin/api/api-key",
  "/resin/vpn/api-key",
  "/resin/vpn/production",
  "/resin/vpn/sentry/dsn",
  "/resin/proxy/api-key",
]
