[template]
src = "env.tmpl"
dest = "/usr/src/app/config/env"
keys = [
  "API_SERVICE_API_KEY",
  "BALENA_API_HOST",
  "BALENA_ROOT_CA",
  "BALENA_VPN_GATEWAY",
  "PRODUCTION_MODE",
  "PROXY_SERVICE_API_KEY",
  "SENTRY_DSN",
  "VPN_KEEPALIVE_FREQUENCY",
  "VPN_KEEPALIVE_TIMEOUT",
  "VPN_SERVICE_API_KEY"
]
